FROM centos

COPY index.html /var/www/html/
RUN yum update -y
RUN yum install httpd -y
# CMD firewall-cmd --permanent --add-service=http
# CMD firewall-cmd --reload
# CMD systemctl start httpd
  ENTRYPOINT httpd -D FOREGROUND

